name: Integração Contínua

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Ativar Checkout
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Instalar Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "1.2.2"
      - run: poetry --version

      - name: Executa os teste unitários
        run: poetry run pytest
