name: Integração Contínua

on: push
jobs:
  test:
  runs-on: ubuntu-latest
  steps:
    - name: Ativar Checkout
      uses: actions/checkout@v2

    - name: Instalar Python
      uses: actions/setup-python@v2
        python-version: 3.9w
